steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/tech-rnd-project/nginx", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/tech-rnd-project/nginx"]
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
  - -c
  - |
    docker push gcr.io/tech-rnd-project/nginx &&
    docker image inspect gcr.io/tech-rnd-project/nginx --format '{{index .RepoDigests 0}}' > image-digest.txt &&
    cat image-digest.txt
  id: push
  
- name: gcr.io/tech-rnd-project/kritis-signer
  entrypoint: /bin/bash
  args:
  - -c
  - |
    /kritis/signer \
    -v=10 \
    -alsologtostderr \
    -image=$(/bin/cat image-digest.txt) \
    -policy=./vulnz-signing-policy.yaml \
    -kms_key_name=${_KMS_KEY_NAME} \
    -kms_digest_alg=${_KMS_DIGEST_ALG} \
    -note_name=${_NOTE_NAME}
  waitFor: ['push']
  id: vulnsign
    
- id: 'create-attestation'
  name: 'gcr.io/tech-rnd-project/binauthz-attestation:latest'
  args:
    - '--artifact-url'
    - 'gcr.io/tech-rnd-project/hello-world:latest'
    - '--attestor'
    - 'projects/tech-rnd-project/attestors/my-binauthz-attestor'
    - '--keyversion'
    - 'projects/tech-rnd-project/locations/global/keyRings/binauthz-keys/cryptoKeys/codelab-key/cryptoKeyVersions/1'
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --image=gcr.io/tech-rnd-project/hello-world:latest
  - --location=us-central1-a
  - --cluster=cluster-1
  
substitutions:
 _KMS_KEY_NAME: projects/tech-rnd-project/locations/global/keyRings/binauthz-keys/cryptoKeys/codelab-key/cryptoKeyVersions/1
 _KMS_DIGEST_ALG: SHA256
 _NOTE_NAME: projects/tech-rnd-project/notes/my-attestor-note 
